plugin: amazon.aws.ec2
regions: [ ap-south-1 ]
filters:
  tag:kubernetes.io/cluster/dev-eks: "owned"
  instance-state-name: "running"
compose:
  ansible_user: ec2-user
  ansible_host: private_ip_address
