name: Terraform

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:
env:
  TF_IN_AUTOMATION: true

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_DEV }}
          aws-region: ap-south-1
      - name: Terraform Init
        run: terraform -chdir=Terraform init -input=false
      - name: Terraform Workspace
        run: terraform -chdir=Terraform workspace select dev || terraform -chdir=Terraform workspace new dev
      - name: Terraform Plan
        run: terraform -chdir=Terraform plan -var-file=envs/dev/terraform.tfvars -no-color -out=tfplan-dev.bin
      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-dev
          path: Terraform/tfplan-dev.bin

  apply:
    needs: plan
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    # environment: dev
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_DEV }}
          aws-region: ap-south-1
      - name: Terraform Init
        run: terraform -chdir=Terraform init -input=false
      - name: Terraform Workspace
        run: terraform -chdir=Terraform workspace select dev || terraform -chdir=Terraform workspace new dev
      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan-dev
          path: Terraform
      - name: Terraform Apply
        run: terraform -chdir=Terraform apply -auto-approve tfplan-dev.bin

  destroy-dev:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    # environment: dev
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_DEV }}
          aws-region: ap-south-1
      - name: Terraform Init
        run: terraform -chdir=Terraform init -input=false
      - name: Terraform Workspace
        run: terraform -chdir=Terraform workspace select dev || terraform -chdir=Terraform workspace new dev
      - name: Terraform Destroy
        run: terraform -chdir=Terraform destroy -var-file=envs/dev/terraform.tfvars -auto-approve
